# Generated by Django 2.0.3 on 2018-04-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type_acceptance_testing_column_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_acceptance_testing_column', to='backend.Column'),
        ),
        migrations.AlterField(
            model_name='board',
            name='type_left_border_column_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_left_border_column', to='backend.Column'),
        ),
        migrations.AlterField(
            model_name='board',
            name='type_priority_column_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_priority_column', to='backend.Column'),
        ),
        migrations.AlterField(
            model_name='board',
            name='type_right_border_column_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_right_border_column', to='backend.Column'),
        ),
        migrations.AlterField(
            model_name='project',
            name='board_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Board'),
        ),
    ]
