# Generated by Django 2.0.3 on 2018-03-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_critical_cards_n_days',
        ),
    ]
