# Generated by Django 2.0.3 on 2018-03-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_display_critical_cards_n_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developergroupmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='developergroupmembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
